name: chat_application
description: "FYP project"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.5.1
  image_picker: ^1.1.2
  share_plus: ^10.1.3
  intl: ^0.20.1
  flutter_rating_bar: ^4.0.1
  cloud_functions: ^5.2.0
  shimmer: ^3.0.0
  crypto: ^3.0.6
  http: ^1.4.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  timeago: ^3.2.2
  firebase_storage: ^12.4.5
  url_launcher: ^6.3.1
  file_picker: ^10.2.0
  emoji_picker_flutter: ^4.3.0
  cloudinary_url_gen: ^1.7.0
  cloudinary_api: ^1.1.0
  geolocator: ^11.0.0
  permission_handler: ^10.4.0
  google_maps_flutter: ^2.2.5
  geocoding: ^2.0.1
  geolocator_web: 3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
 
  adaptive_icon_background: "#FFFFFF" # Background color for adaptive icons
 
flutter:
  uses-material-design: true
  assets:
    - assets/Images/


