// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJtZV5pOtiEyO1bUZycyeY6270Ts3L3E',
    appId: '1:461435598818:web:e57158714a31d269986bbb',
    messagingSenderId: '461435598818',
    projectId: 'chatapp-76675',
    authDomain: 'chatapp-76675.firebaseapp.com',
    storageBucket: 'chatapp-76675.firebasestorage.app',
    measurementId: 'G-GDKKXLSH1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoqtVNaUULkbz3VsrBz1MafRVO2S2nEw',
    appId: '1:461435598818:android:61c3f55f0bc973d8986bbb',
    messagingSenderId: '461435598818',
    projectId: 'chatapp-76675',
    storageBucket: 'chatapp-76675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIa9iApxDHunVofcN-lcTjH-cdyXp_gns',
    appId: '1:461435598818:ios:2a41de04afa1dec9986bbb',
    messagingSenderId: '461435598818',
    projectId: 'chatapp-76675',
    storageBucket: 'chatapp-76675.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIa9iApxDHunVofcN-lcTjH-cdyXp_gns',
    appId: '1:461435598818:ios:2a41de04afa1dec9986bbb',
    messagingSenderId: '461435598818',
    projectId: 'chatapp-76675',
    storageBucket: 'chatapp-76675.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMJtZV5pOtiEyO1bUZycyeY6270Ts3L3E',
    appId: '1:461435598818:web:86613279a0ab4a35986bbb',
    messagingSenderId: '461435598818',
    projectId: 'chatapp-76675',
    authDomain: 'chatapp-76675.firebaseapp.com',
    storageBucket: 'chatapp-76675.firebasestorage.app',
    measurementId: 'G-DGE3XK20QV',
  );
}
